
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsvizquyprrchbdvknjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzdml6cXV5cHJyY2hiZHZrbmp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NTczNDUsImV4cCI6MjA1ODEzMzM0NX0.p9B91BoTIbmRzCQJtfcQhaO3qQwSH5DlP_5lGccevKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'flapabay-auth-token',
  }
});
